python-daemon (1.5.2-1) unstable; urgency=low

  * Initial release

 -- Andrey Tatarinov <a.tatarinov@hh.ru>  Mon, 23 Nov 2009 12:56:22 +0300

